version: 0.2

phases:
  install:
    commands:
      - echo Installing dependency...
      - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      - nvm install 16.13.0
      - nvm install node
      - npm install -g next
      - yarn
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - echo Compiling the Node.js code
      - next build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
